// Code generated by "stringer -type Subsystem"; DO NOT EDIT.

package unpi

import "strconv"

const _Subsystem_name = "S_RES0S_SYSS_MACS_NWKS_AFS_ZDOS_SAPIS_UTILS_DBGS_APPS_RCAFS_RCNS_RCN_CLIENTS_BOOTS_ZIPTESTS_DEBUGS_PERIPHERALSS_NFCS_PB_NWK_MGRS_PB_GWS_PB_OTA_MGRS_BLE_SPNPS_BLE_HCIS_RESV01S_RESV02S_RESV03S_RESV04S_RESV05S_RESV06S_RESV07S_RESV08S_SRV_CTR"

var _Subsystem_index = [...]uint8{0, 6, 11, 16, 21, 25, 30, 36, 42, 47, 52, 58, 63, 75, 81, 90, 97, 110, 115, 127, 134, 146, 156, 165, 173, 181, 189, 197, 205, 213, 221, 229, 238}

func (i Subsystem) String() string {
	if i >= Subsystem(len(_Subsystem_index)-1) {
		return "Subsystem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Subsystem_name[_Subsystem_index[i]:_Subsystem_index[i+1]]
}
